services:
  - type: web
    name: pet-feeder-dashboard
    env: node
    buildCommand: cd rep-dashboard && npm install
    startCommand: cd rep-dashboard && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: MQTT_HOST
        sync: false
      - key: MQTT_PORT
        sync: false
      - key: MQTT_USERNAME
        sync: false
      - key: MQTT_PASSWORD
        sync: false