#pragma once

// Certificado CA do servidor Mosquitto MQTT
const char* MQTT_CA_CERT = \
"-----BEGIN CERTIFICATE-----\n" \
"MIIDgzCCAmugAwIBAgIUR8VrpyjAUYLfFlqgvpA3NCLOw8AwDQYJKoZIhvcNAQEL\n" \
"BQAwUTELMAkGA1UEBhMCQlIxCzAJBgNVBAgMAlNQMRIwEAYDVQQHDAlTYW8gUGF1\n" \
"bG8xDzANBgNVBAoMBlVtYnJlbDEQMA4GA1UEAwwHTVFUVCBDQTAeFw0yNTExMTUx\n" \
"NjE0NDdaFw0zNTExMTMxNjE0NDdaMFExCzAJBgNVBAYTAkJSMQswCQYDVQQIDAJT\n" \
"UDESMBAGA1UEBwwJU2FvIFBhdWxvMQ8wDQYDVQQKDAZVbWJyZWwxEDAOBgNVBAMM\n" \
"B01RVFQgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCioB5ApI5q\n" \
"pdtIMHKEfaiFvxJ3EFY38AF3ShX4WP5EVspVVcLpOJfKFqtDySMfN9b606zxikZd\n" \
"W/e8wHUESbqjW5FIkUh1TKIwfrk14gpeIQdeYVNlLGwYsDoYTVq63DE+b77xb57a\n" \
"c27uRBabCcOA+eTnHeG50ZJMgV7NA4XEqTPm+63N6OZR+Kvy0QfTMtbkhiWInWTi\n" \
"egGjGAmGnc6SZ8YTB2F1k62LIQRDrumdQy/8icWki+gif6KSVrN8d1n49QLMZ4cN\n" \
"hxDvre4MyBvhdHBanQA8Y49D+a0Ve9/Y4v1L6xL3u0VhdJ1baEEVSxcLQBd++V/X\n" \
"60D8goU44RQrAgMBAAGjUzBRMB0GA1UdDgQWBBQdpCHq26TlavGXnHoBVww+cBfK\n" \
"KDAfBgNVHSMEGDAWgBQdpCHq26TlavGXnHoBVww+cBfKKDAPBgNVHRMBAf8EBTAD\n" \
"AQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAPfabyLOvmHnPeYMfqscGI1Ge4bgE08BGX\n" \
"I1xR0t/GZcoEWJQzOiXc/OwfsTAwWkrF4Ubc45D2wcxKw0lz84kHUoqQFFkeIOMY\n" \
"4I0CMwkXl62qCBUmvfPW2If+A+KEda8ubFVgddWfiXeDjfyjEJbAhoycvr9zFmv1\n" \
"gKiynqEJPnNnsPfV2bTRFI+wp3coxAsCOBlGRIIzmSl1XHzgefVmnZfYzELl+g3D\n" \
"BL4H2yA7Uq6vWpW4VOIyPCLAGuL6HotBkqjb3VO5BoqADKPbr5dsS/cg9I91rZZt\n" \
"gCtDmwltHwVs+x7taXl1Gda+MSFulvJCClE8iEJ6T916MzH9OO+w\n" \
"-----END CERTIFICATE-----\n";